driver:
  name: vagrant

provisioner:
  name: chef_zero
  client_rb:
    treat_deprecation_warnings_as_errors: true
    silence_deprecation_warnings:
    # There's a deprecation warning in the homebrew cookbook right now
    # Might be gone with Chef 14.5
    - chef-25

verifier:
  name: inspec

platforms:
  - name: centos-6
  - name: centos-7
  - name: debian-8
  - name: debian-9
  - name: fedora-28
  - name: opensuse-leap-42
  - name: ubuntu-14.04
  - name: ubuntu-16.04
  - name: ubuntu-18.04
  - name: freebsd-11.0

suites:
- name: default
  run_list:
  - recipe[test]
